<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

class FoodsFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        static $counter = 0;
        $restID = [
            1,
            3,
            5,
            1,
            3,
            5,
            1,
            3,
            5,
            1,
            3,
            5,
            2,
            4,
            6,
            9,
            6,
            2,
            4,
            6,
            9,
            1,
            2,
            4,
            5,
            6,
            9,
            1,
            1,
            2,
            4,
            6,
            9,
            1,
            4,
            1,
            1,
            2,
            4,
            6,
            9,
            9,
            10,
            11,
            10,
            11,
            11,
            7,
            7,
            7,
            8,
            8,
            8,
            8,
            8,
            12,
            12,
            12,
            12,
            12
        ];
        $termNev= [
            "Hawaii pizza",
            "Hawaii pizza",
            "Hawaii pizza",
            "Hawaii pizza extra ananásszal",
            "Sonkás pizza",
            "Sonkás-Gombás pizza",
            "Sonkás-Kukoricás pizza",
            "Szalámis pizza",
            "BBQ pizza",
            "Vegán pizza",
            "Négysajtos pizza",
            "Tonhalas pizza",
            "Mexikói csirkés tészta",
            "Bolognai tészta",
            "Milánói tészta",
            "Carbonara tészta",
            "Cékla-Feta krémes tészta",
            "Babgulyás",
            "Babgulyás",
            "Csirkepöri nokedlivel",
            "Noki-Pöri",
            "Tökfőzelék",
            "Hagymás bab",
            "Lencsefőzelék",
            "Krumplifőzelék",
            "Spenótfőzelék",
            "Zöldbabfőzelék",
            "Tojásleves",
            "Húsleves",
            "Húsleves",
            "Húsleves",
            "Gyümileves",
            "Gyümölcsleves",
            "Fokhagymakrémleves",
            "Fokhagymarémleves",
            "Hatlapos",
            "Tizenkétlapos",
            "Négerkocka",
            "Lajcsi szelet",
            "Tiramisu",
            "Tiramisu",
            "Bejgli",
            "Sajtburesz",
            "Sajtburesz",
            "Dupla Sajtburesz",
            "Big Mac",
            "Dupla Big Mac",
            "Sajtburger",
            "Zinger burger",
            "Grander burger",
            "Cheddar Cheese Ring Lover",
            "Chicken Bacon King",
            "Bacon King",
            "Nuggets Burger",
            "Chili Cheese Crispy Chicken",
            "Csepregi kolesz menü",
            "Kelbimbó főzelék",
            "Tökfőzelék",
            "Kiwis pizza",
            "Csirkemáj"
        ];
        $leiras= [
            "Nagyon fincsi",
            "Legjobb pizza",
            "Kedvencem",
            "Hihetetlenül finom",
            "Kezdésnek nem rossz",
            "A gomba helyett akkor már inkább kukorica",
            "Egész jó, csak kéne még rá ananász",
            "Ló étvágyat!",
            "Fincsiiii!",
            "Fúúúúúj",
            "Akár jó is lehet",
            "Nekem 8",
            "Nem rossz",
            "Hagyományos",
            "Egs",
            "Fincsi",
            "Ehhh?",
            "Bogrács?",
            "Fincsi",
            "Van aki ezt nem nokival eszi??",
            "Fincsi",
            "Amúgy fúj",
            "Jóféle",
            "Ehhh",
            "Klasszikus",
            "Maybe",
            "Inkább ne",
            "Fincsi",
            "Nagyi kedvence",
            "Nagyi kedvence",
            "Nagyi kedvence",
            "Fúj",
            "Fúj",
            "Fincsi",
            "Fincsi",
            "Fincsi",
            "Dupla vagy semmi",
            "Igen",
            "Lagziba kiváló",
            "Fincsi",
            "Fincsi",
            "Diós / Mákos / Gesztenyés",
            "Fincsi",
            "Fincsi",
            "Duplán Fincsi",
            "Egészséges!",
            "Duplán egészséges!",
            "Legalább ebben csirke van",
            "Amúgy fincsi",
            "Jóféle",
            "Nem kicsi",
            "Inkább BK appból rendeld",
            "Ezt is inkább BK appból rendeld",
            "Amúgy egész korrekt ár",
            "Csíp!!",
            "Un-Dó-Rííítóó",
            "Mennem kell hányni",
            "Soha!!",
            "Mivan??",
            "Nop"
        ];
        $ar= [
            3400,
            2950,
            3600,
            3850,
            2800,
            3200,
            3200,
            3100,
            3800,
            1500,
            2500,
            3600,
            2500,
            2350,
            2600,
            2550,
            1890,
            4500,
            3700,
            2800,
            3200,
            1890,
            2300,
            2600,
            3200,
            2600,
            1890,
            1620,
            1234,
            4321,
            3600,
            990,
            1200,
            1500,
            1490,
            700,
            950,
            350,
            280,
            480,
            650,
            1100,
            690,
            690,
            1290,
            1890,
            2490,
            990,
            1890,
            2490,
            2990,
            2440,
            2510,
            750,
            1540,
            2000,
            1800,
            1890,
            2390,
            2890

        ];
        $cid=[
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            2,
            2,
            2,
            2,
            2,
            3,
            3,
            3,
            3,
            4,
            4,
            4,
            4,
            4,
            4,
            5,
            5,
            5,
            5,
            5,
            5,
            5,
            5,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            8,
            8,
            8,
            8,
            8

        ];
        return [
            'r_id' => $restID[$counter],
            'f_name'=>$termNev[$counter],
            'c_id'=>$cid[$counter],
            'description'=>$leiras[$counter],
            'price'=>$ar[$counter++],
            'available'=>1
        ];
    }
}
